openapi: 3.0.3
info:
  title: Live Drops API
  version: 1.0.0
servers:
  - url: https://api.example.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /v1/creators/{creatorId}/follow:
    post:
      summary: Follow creator
      parameters:
        - in: path
          name: creatorId
          schema: { type: string }
          required: true
      responses:
        '200': { description: Followed }
    delete:
      summary: Unfollow creator
      parameters:
        - in: path
          name: creatorId
          schema: { type: string }
          required: true
      responses:
        '200': { description: Unfollowed }

  /v1/browse/drops:
    get:
      summary: Browse drops
      parameters:
        - in: query
          name: status
          schema: { type: string, enum: [live, scheduled, ended] }
        - in: query
          name: creatorId
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, default: 20, minimum: 1, maximum: 100 }
        - in: query
          name: cursor
          schema: { type: string }
      responses:
        '200':
          description: OK

  /v1/orders:
    post:
      summary: Place order (idempotent)
      parameters:
        - in: header
          name: Idempotency-Key
          schema: { type: string }
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId, dropId, productId, quantity, payment]
              properties:
                userId: { type: string }
                dropId: { type: string }
                productId: { type: string }
                quantity: { type: integer, minimum: 1 }
                payment:
                  type: object
                  required: [method, paymentToken]
                  properties:
                    method: { type: string, enum: [card] }
                    paymentToken: { type: string }
      responses:
        '201': { description: Paid }
        '202': { description: Pending }
        '409': { description: Sold out }
